export const seedUsers = {
  admin: {
    email: process.env.SEED_ADMIN_EMAIL,
    password: process.env.SEED_ADMIN_PASSWORD,
    firstName: 'Admin',
    lastName: 'MedBook',
  },
  doctors: [
    {
      email: process.env.SEED_DOCTOR1_EMAIL,
      password: process.env.SEED_DOCTOR1_PASSWORD,
      firstName: 'Sarah',
      lastName: 'Johnson',
      phone: '+1234567890',
      specialty: 'Cardiology',
      bio: 'Experienced cardiologist with over 15 years of practice. Specializes in heart disease prevention and treatment.',
      consultationFee: 150,
      affiliation: 'City General Hospital',
      yearsOfExperience: 15,
      clinicAddress: '123 Medical Center Dr, Suite 456',
      clinicContactPerson: 'Jane Smith',
      clinicPhone: '+1234567891',
    },
    {
      email: process.env.SEED_DOCTOR2_EMAIL,
      password: process.env.SEED_DOCTOR2_PASSWORD,
      firstName: 'Omar',
      lastName: 'Benali',
      phone: '+1234567893',
      specialty: 'Neurology',
      bio: 'Board-certified neurologist specializing in migraines, epilepsy, and movement disorders with 10 years of experience.',
      consultationFee: 180,
      affiliation: 'Central Medical Center',
      yearsOfExperience: 10,
      clinicAddress: '456 Neuro Ave, Suite 12',
      clinicContactPerson: 'Ahmed Malik',
      clinicPhone: '+1234567894',
    },
    {
      email: process.env.SEED_DOCTOR3_EMAIL,
      password: process.env.SEED_DOCTOR3_PASSWORD,
      firstName: 'Leila',
      lastName: 'Moussaoui',
      phone: '+1234567895',
      specialty: 'General Practice',
      bio: 'General practitioner with a patient-first approach, providing comprehensive primary care for all ages.',
      consultationFee: 80,
      affiliation: 'HealthFirst Clinic',
      yearsOfExperience: 8,
      clinicAddress: '789 Health Blvd, Ground Floor',
      clinicContactPerson: 'Fatima Zahra',
      clinicPhone: '+1234567896',
    },
  ],
};
